class COLUMN_NAMES:
    TITLE = 'title'
    KEYWORDS = 'keywords'
    CAST = 'cast'
    GENRES = 'genres'
    DIRECTOR = 'director'
    FEATURES = 'features'

class CONTENT_BASED_FILTERING:
    FILE_NAME = "movie_dataset.xls"
    RECOMMENDED_MOVIES_COUNT= 20
    MINIMUM_THRESHOLD = 70
    FILTER_COLUMNS = [COLUMN_NAMES.KEYWORDS, COLUMN_NAMES.CAST, COLUMN_NAMES.GENRES, COLUMN_NAMES.DIRECTOR]

class ERRORS:
    MOVIE_NOT_FOUND = 'MOVIE_NOT_FOUND'
    NO_SIMILAR_MOVIES = 'NO_SIMILAR_MOVIES'

class GUI:
    LANG_FILE = "./view/en_us.json"
    TITLE_FG = '#000000'
    TITLE_BG = '#f5c518'
    TITLE_FONT = ("Roboto", 24, "bold")
    MOVIE_ITEM_FG = '#383127'
    MOVIE_ITEM_BG = '#E4DBBF'
